// toasts
export const ADD_TOAST = "ADD_TOAST";
export const REMOVE_TOAST = "REMOVE_TOAST";

// quotes
export const GET_QUOTES_REQUEST = "GET_QUOTES_REQUEST";
export const GET_QUOTES_SUCCESS = "GET_QUOTES_SUCCESS";
export const GET_QUOTES_FAILURE = "GET_QUOTES_FAILURE";

// products
export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE";

// orders
export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAILURE = "GET_ORDERS_FAILURE";
export const CHANGE_ORDER_ITEM_STATUS_REQUEST =
  "CHANGE_ORDER_ITEM_STATUS_REQUEST";
export const CHANGE_ORDER_ITEM_STATUS_SUCCESS =
  "CHANGE_ORDER_ITEM_STATUS_SUCCESS";
export const CHANGE_ORDER_ITEM_STATUS_FAILURE =
  "CHANGE_ORDER_ITEM_STATUS_FAILURE";
export const APPROVE_CANCEL_ORDER_ITEM = "APPROVE_CANCEL_ORDER_ITEM";
export const REJECT_CANCEL_ORDER_ITEM = "REJECT_CANCEL_ORDER_ITEM";

// notification
export const GET_NOTIFICATIONS_REQUEST = "GET_NOTIFICATIONS_REQUEST";
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
export const GET_NOTIFICATIONS_FAILURE = "GET_NOTIFICATIONS_FAILURE";
export const INCREMENT_UNREAD_NOTIFICATION_COUNT =
  "INCREMENT_UNREAD_NOTIFICATION_COUNT";
export const CLEAR_UNREAD_NOTIFICATION_COUNT =
  "CLEAR_UNREAD_NOTIFICATION_COUNT";

// ui
export const SHOW_SURE_MODAL = "SHOW_SURE_MODAL";
export const HIDE_SURE_MODAL = "HIDE_SURE_MODAL";
